# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorito',
            options={'ordering': ['alumno', 'vendedor']},
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='formas_de_pago',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='JUNAEB',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='dedito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='efectivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Alumno'),
        ),
        migrations.AlterField(
            model_name='favorito',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Vendedor'),
        ),
        migrations.DeleteModel(
            name='FormasDePago',
        ),
    ]
