# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170527_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
