# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170527_2200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendedor',
            old_name='dedito',
            new_name='debito',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(max_length=200),
        ),
    ]
