# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170528_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='foto',
            field=models.ImageField(default='img/avatarEstudiante3.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(default='img/avatarPenguin.png', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'normal'), (2, 'vegetariano'), (3, 'vegano')], default=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='foto',
            field=models.ImageField(default='img/bread', upload_to='media'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='foto',
            field=models.ImageField(default='img/avatarVendedor3.png', upload_to='media'),
        ),
    ]
